### ISSUE TITLE
2-chain DiemBFT

### ISSUE THREAD

**Issue by zekun000** [diem/dip#201]
Research team has been working on DiemBFT v4 and one of the major improvement is to achieve 2-chain commit instead of 3-chain leveraging existing round synchronization mechanism.

This issue is intended to track the development of the corresponding DIP https://github.com/diem/dip/blob/main/dips/dip-201.md.

**Comment by dahliamalkhi** [comment]
I'll be the Maintainer-Manager for this DIP-201.
